---
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  pause_pools:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Get all resource groups with tag "opplæring"
            # For each group: Get all workspaces
            # For each workspace, get all pools
            # For each pool: Check status. If not paused then try to pause.

            RESOURCE_GROUPS=$(az group list --tag opplæring --query "[].name" -o tsv)
            while IFS= read -r GROUP_NAME ; do
              echo "Checking for Synapse Workspaces in $GROUP_NAME";
              WORKSPACES=$(az synapse workspace list -g $GROUP_NAME --query "[].name" -o tsv)
              while IFS= read -r WORKSPACE_NAME ; do
                echo "Checking for SQL Pools in $WORKSPACE_NAME";
                SQL_POOLS=$(az synapse sql pool list -g $GROUP_NAME --workspace-name $WORKSPACE_NAME --query "[].name" -o tsv)
                while IFS= read -r POOL_NAME ; do
                  echo "Checking status for pool $POOL_NAME";
                  POOL_STATUS=$(az synapse sql pool show --query "status" --name $POOL_NAME --workspace-name $WORKSPACE_NAME -g $GROUP_NAME)
                  if [[ "$POOL_STATUS" == "Paused" ]]; then
                    echo "Pool is already paused"
                  else
                    echo "Pool is not paused ($POOL_STATUS)"
                    az synapse sql pool pause --name $POOL_NAME --workspace-name $WORKSPACE_NAME -g $GROUP_NAME
                  fi
                done <<< "$SQL_POOLS"
              done <<< "$WORKSPACES"
            done <<< "$RESOURCE_GROUPS"
